### ISSUE TITLE
Calculation of force on plate settlers

### ISSUE THREAD

**Issue by Galantino** [AguaClara/horizontal_filtration#2]
-can a simple calculation of force based on upflow and hydrostatics be determined?
-where does the angle matter here?

**Comment by ethan92429** [comment]
My guess is that the most force will be a drag force during backwash. If you assume the full pressure of backwash across the area of the settler, you would get a conservative high end for the total force on all of the plate settlers: (headloss during backwash) x (area of plate settler)... at the high end this might be: ρgh*w_plate_settler*L_plate_settler = 1000 kg/m^3 * 9.8 m/s^2 * 2 m * 0.03 m *1 m = 588 Newtons = 132 lbs for a 3 cm wide plate settler (horizontal) per meter of length of filter. Or 1.3 lbs/ cm. This means if you have 10 settlers, if you can tie them together at the end, it may only be 0.13 lbs/cm.
